openapi: 3.0.3
info:
  title: AGTA IT API Documentation
  description: |
    API complète pour la gestion des items avec authentification, validation des données
    et pagination. Cette documentation décrit tous les endpoints disponibles pour interagir
    avec les ressources d'items.
  version: 1.0.0
  contact:
    name: Support API
    email: support@example.com
    phone: '+237 655 646 688'
    address:
      street: ''
      city: 'Yaounde'
      state: 'Centre'
      country: 'Cameroun'

  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000/
    description: Serveur de développement local
  - url: http://localhost:3000/api/v1
    description: Serveur de développement local avec préfixe API v1
  - url: https://api.example.com/api/v1
    description: Serveur de production avec préfixe API v1

tags:
  - name: Items
    description: Opérations sur les items

paths:
  /items:
    $ref: './paths/items.yaml#/items'
  /items/{id}:
    $ref: './paths/items.yaml#/items/{id}'

components:
  schemas:
    Item:
      $ref: './schemas/item.yaml'

  parameters:
    $ref: './components/parameters.yaml'

  responses:
    $ref: './components/responses.yaml'

  securitySchemes:
    $ref: './security/bearerAuth.yaml'

security:
  - BearerAuth: []

externalDocs:
  description: Documentation complète de l'API
  url: https://docs.example.com/api
